drop table if exists `reptile` CASCADE;

create table `reptile` (
   `id` bigint generated by default as identity,
    `age` integer,
    `gender` varchar(255),
    `is_arboreal` boolean,
    `is_insectivore` boolean,
    `name` varchar(255),
    `specie` varchar(255),
    primary key (id)
);